In [1]:
import numpy as np
from matrix.rectangular_matrix import RandomMatrix as RM

In [2]:
example_a = RM(2,2)
print( example_a)
print(f'With components \n {example_a.matrix}')
print(f'The rank is {example_a.rank()}')
print(f'The trace is {example_a.trace()}')
print(f'The inverse matrix is \n {example_a.inverse()}')

A random matrix  of size  2x2 has been generated
With components 
 [[30 35]
 [62 32]]
The rank is 2
The trace is 62
The inverse matrix is 
 [[-0.02644628  0.02892562]
 [ 0.05123967 -0.02479339]]


In [3]:
example_a.transpose()

array([[30, 62],
       [35, 32]])

In [5]:
np.linalg.eig(example_a.matrix*example_a.transpose())

(array([-1208.8855336,  3132.8855336]),
 array([[-0.7171331 , -0.69693623],
        [ 0.69693623, -0.7171331 ]]))

In [7]:
np.linalg.eig(example_a.transpose()*example_a.matrix)

(array([-1208.8855336,  3132.8855336]),
 array([[-0.7171331 , -0.69693623],
        [ 0.69693623, -0.7171331 ]]))